Demonstrate rust_prost_library transitive deps error
In certain situations, types from transitive dependencies are included
in the generated .lib.rs file, potentially causing compilation errors.
The simplest repro I've found is a.proto includes b.proto includes
c.proto includes d.proto, with a, b, and c in the same namespace and d
in a parent namespace.

This can be fixed by including the types in d in prost_build's
extern_path option, but I'm not sure if this is a rules_rust or
prost_build bug.

```
$ bazelisk build //private/tests/transitive_dependencies:a_rs_proto
ERROR: rules_rust/extensions/prost/private/tests/transitive_dependencies/BUILD.bazel:8:14: Compiling Rust rlib a_proto (1 file) failed: (Exit 1): process_wrapper failed: error executing Rustc command (from target //private/tests/transitive_dependencies:a_proto) bazel-out/k8-opt-exec-ST-d57f47055a04/bin/external/rules_rust+/util/process_wrapper/process_wrapper --arg-file bazel-out/k8-fastbuild/bin/external/+rust_ext+rrprd__axum-core-0.4.3/_bs.linksearchpaths ... (remaining 126 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
error[E0433]: failed to resolve: unresolved import
  --> bazel-out/k8-fastbuild/bin/private/tests/transitive_dependencies/a_proto.lib.rs:15:46
   |
15 |         pub d: ::core::option::Option<super::google::protobuf::Empty>,
   |                                              ^^^^^^
   |                                              |
   |                                              unresolved import
   |                                              help: a similar path exists: `duration_proto::google`

error: aborting due to 1 previous error
```

`bazel-bin/private/tests/transitive_dependencies/a_proto.lib.rs`
contains the A3 message despite it being defined in a different file:

```
// @generated

pub use a2_proto;
pub use b_proto;
pub use duration_proto;
pub use timestamp_proto;
pub use types_proto;
pub mod a {
    // @generated
    // This file is @generated by prost-build.
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct A3 {
        #[prost(message, optional, tag = "1")]
        pub d: ::core::option::Option<super::google::protobuf::Empty>,
    }
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct A {
        #[prost(string, tag = "1")]
        pub name: ::prost::alloc::string::String,
        #[prost(message, optional, tag = "2")]
        pub b: ::core::option::Option<::b_proto::a::b::B>,
        #[prost(message, optional, tag = "3")]
        pub timestamp: ::core::option::Option<::timestamp_proto::google::protobuf::Timestamp>,
        #[prost(message, optional, tag = "4")]
        pub duration: ::core::option::Option<::duration_proto::google::protobuf::Duration>,
        #[prost(message, optional, tag = "5")]
        pub types: ::core::option::Option<::types_proto::Types>,
        #[prost(message, optional, tag = "6")]
        pub a2: ::core::option::Option<::a2_proto::a::A2>,
    }
    // @@protoc_insertion_point(module)
}
```